package parselang.parser.data;

/**
 * A nonterminal in the parse process
 */
public final class NonTerminal extends Node {

    /**
     * Returns whether this Nonterminal was automatically generated from a star node
     * @return true if it was automatically generated
     */
    public boolean wasGeneratedByStar() {
        return status;
    }

    /**
     * @inheritDoc
     */
    @Override
    public Node copy() {
        return new NonTerminal(name, status);
    }

    private final String name;

    /**
     * Creates a new nonterminal
     * @param name the nonterminal's name
     * @param autogenerated whether the nonterminal was automatically generated while processing a kleene star token
     */
    public NonTerminal(String name, boolean autogenerated) {
        this.name = name;
        this.status = autogenerated;
    }

    private final boolean status;

    /**
     * Returns the name of this nonterminal
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @inheritDoc
     */
    @Override
    public String toString() {
        return name;
    }

    /**
     * @inheritDoc
     */
    @Override
    public boolean equals(Object other) {
        if (!(other instanceof NonTerminal)) {
            return false;
        }
        return name.equals(((NonTerminal) other).getName());
    }

    /**
     * @inheritDoc
     */
    @Override
    public int hashCode() {
        return name.hashCode();
    }


}
